### ISSUE TITLE
wpyscripts.common.wetest_exceptions.WeTestSDKError: Recv Data From SDK timeout

### ISSUE THREAD

**Issue by hzg17** [Tencent/GAutomator#15]
运行自己写的代码报错
Traceback (most recent call last):
  File "/Users/h/自动化相关/GAutomatorTest/wpyscripts/KoaTest/test.py", line 42, in <module>
    version=engine.get_sdk_version()
  File "/Users/h/自动化相关/GAutomatorTest/wpyscripts/wetest/engine.py", line 119, in get_sdk_version
    ret = self.socket.send_command(Commands.GET_VERSION, 1)
  File "/Users/h/自动化相关/GAutomatorTest/wpyscripts/common/socket_client.py", line 80, in send_command
    raise WeTestSDKError("Recv Data From SDK timeout")
wpyscripts.common.wetest_exceptions.WeTestSDKError: Recv Data From SDK timeout

**Comment by wukenaihe** [comment]
@hzg17 
检查下你的apk是否已经集成sdk，集成sdk的游戏是否已经拉起。sdk拉起后，会在手机端监听27019端口。adb shell netstat |grep 27019是否已经打开。

**Comment by hzg17** [comment]
@wukenaihe 执行adb shell netstat |grep 27019后，好用了不报错了，谢谢

**Comment by wukenaihe** [comment]
@hzg17 这种情况怀疑是adb出了问题

**Comment by hzg17** [comment]
@wukenaihe 好谢谢

**Comment by hzg17** [comment]
@wukenaihe 能加个qq吗？有问题比较方便沟通
