### ISSUE TITLE
如何进行demo调试，一直失败

### ISSUE THREAD

**Issue by youshiki123** [Tencent/GAutomator#22]
1、是否demo需要用手机拉起，用模拟器是否可以
2.使用sample-test脚本一直调试失败
3、请问有没有想过人员调试成功过

**Comment by wukenaihe** [comment]
@youshiki123 模拟器我们这边尝试过，是可以的。你adb环境是否准备妥当，adb是否能连上模拟器？有没有报错信息？

**Comment by youshiki123** [comment]
@wukenaihe 可以否留个QQ方便沟通，我试试adb连上去是否ok

**Comment by youshiki123** [comment]
@wukenaihe 已经连接好adb了，但是还是运行你们提供的脚本报错，麻烦帮忙看看是什么问题？

C:\Python27\python.exe E:/svn/python/GAutomator/sample_test.py
2017-05-16 11:52:19,286 - INFO - manager.py:104 - wpyscripts.manager - None
2017-05-16 11:52:19,286 - INFO - manager.py:106 - wpyscripts.manager - host: 127.0.0.1 port: 53001
Traceback (most recent call last):
  File "E:/svn/python/GAutomator/sample_test.py", line 6, in <module>
    from testcase.tools import *
  File "E:\svn\python\GAutomator\testcase\tools.py", line 12, in <module>
    from wpyscripts.tools.baisc_operater import *
  File "E:\svn\python\GAutomator\wpyscripts\tools\baisc_operater.py", line 22, in <module>
    engine = manager.get_engine()
  File "E:\svn\python\GAutomator\wpyscripts\manager.py", line 107, in get_engine
    get_engine.instance = GameEngine(hostip, local_port)
  File "E:\svn\python\GAutomator\wpyscripts\wetest\engine.py", line 108, in __init__
    self.socket = SocketClient(self.address, self.port)
  File "E:\svn\python\GAutomator\wpyscripts\common\socket_client.py", line 23, in __init__
    self.socket.connect((self.host, self.port))
  File "C:\Python27\lib\socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 10061]

**Comment by wukenaihe** [comment]
@youshiki123 这个用例需要手动拉起

**Comment by youshiki123** [comment]
好的

**Comment by youshiki123** [comment]
@wukenaihe 如何手动拉起，我按照教程里面命令行或是ide的调试都不行，还是报这个错误

**Comment by wukenaihe** [comment]
@youshiki123 游戏直接点击拉起呗。main.py里面包含了拉起游戏的逻辑。但是测试的脚本sample里面是不包含的。你可以先把demo在模拟器里面拉起来，然后再运行你的脚本

**Comment by youshiki123** [comment]
@wukenaihe 我是按照你上面所得步骤，先demo拉起，然后再运行脚本
还是依然提示那个错误

**Comment by wukenaihe** [comment]
@youshiki123 你是什么模拟器？

**Comment by youshiki123** [comment]
C:\Python27\python.exe E:/svn/python/GAutomator/sample.py
Retry...10054
Retry...10054
Traceback (most recent call last):
  File "E:/svn/python/GAutomator/sample.py", line 21, in <module>
    test()
  File "E:/svn/python/GAutomator/sample.py", line 12, in test
    version=engine.get_sdk_version()
  File "E:\svn\python\GAutomator\wpyscripts\wetest\engine.py", line 124, in get_sdk_version
    ret = self.socket.send_command(Commands.GET_VERSION, 1)
  File "E:\svn\python\GAutomator\wpyscripts\common\socket_client.py", line 87, in send_command
    raise Exception('Socket Error')
Exception: Socket Error

**Comment by youshiki123** [comment]
@wukenaihe 现在端口什么都设置好，代码本身也是ok的，我让其他在用GA的试过，但是还是报下面的错
C:\Python27\python.exe E:/svn/python/GAutomator/sample.py
Retry...10054
Retry...10054
Traceback (most recent call last):
  File "E:/svn/python/GAutomator/sample.py", line 21, in <module>
    test()
  File "E:/svn/python/GAutomator/sample.py", line 12, in test
    version=engine.get_sdk_version()
  File "E:\svn\python\GAutomator\wpyscripts\wetest\engine.py", line 124, in get_sdk_version
    ret = self.socket.send_command(Commands.GET_VERSION, 1)
  File "E:\svn\python\GAutomator\wpyscripts\common\socket_client.py", line 87, in send_command
    raise Exception('Socket Error')
Exception: Socket Error

**Comment by wukenaihe** [comment]
@youshiki123 你QQ多少，实在不行远程调试

**Comment by wukenaihe** [comment]
@youshiki123 发我邮箱好了

**Comment by youshiki123** [comment]
好的

**Comment by gary-lee** [comment]
这个问题解决了么？我也遇到了同样的问题

**Comment by lilin22** [comment]
@youshiki123 @wukenaihe 碰到同样的问题，可否帮忙？我的qq：2622601661

**Comment by araya** [comment]
Demo 尝试。。不行啊。。
D:\Python27\python.exe D:/GAutomator/sample/sample.py
2017-06-10 15:12:17,582 - INFO - manager.py:104 - wpyscripts.manager - None
2017-06-10 15:12:17,601 - INFO - manager.py:106 - wpyscripts.manager - host: 127.0.0.1 port: 53001
2017-06-10 15:12:18,253 - DEBUG - uiautomator_manager.py:34 - wetest - Start UIAutomator
1156 KB/s (587595 bytes in 0.496s)

2017-06-10 15:12:21,286 - DEBUG - uiautomator_manager.py:37 - wetest - Exit uiautomator
Retry...10053
Traceback (most recent call last):
  File "D:/GAutomator/sample/sample.py", line 196, in <module>
    main()
  File "D:/GAutomator/sample/sample.py", line 190, in main
    test_interaction()
  File "D:/GAutomator/sample/sample.py", line 33, in wrapped
    enter = engine.find_element(button)
  File "D:\GAutomator\wpyscripts\wetest\engine.py", line 149, in find_element
Retry...10054
    ret = self.socket.send_command(Commands.FIND_ELEMENTS, [name])
  File "D:\GAutomator\wpyscripts\common\socket_client.py", line 87, in send_command
    raise Exception('Socket Error')
Exception: Socket Error

Process finished with exit code 1
求解决

**Comment by wukenaihe** [comment]
@araya 测试之前，apk需要自己拉起来。sample.py不会拉起apk的

**Comment by araya** [comment]
@wukenaihe  我知道问题在哪了。。模拟器运行不起来，真机可正常运行

**Comment by suqingyue738** [comment]
![default](https://user-images.githubusercontent.com/12101941/32319302-10de4140-bff5-11e7-906b-a829512fb87f.png)
我用的是真机，但是报这个

**Comment by lazydao** [comment]
自己写了启动游戏的代码，结果还是偶尔报 Retry...10053 
感觉这框架很不好用啊

**Comment by lazydao** [comment]
PS C:\Users\Administrator\autoTest> py -2 .\sample.py
2018-03-09 18:12:03,950 - INFO - manager.py:104 - wpyscripts.manager - None
2018-03-09 18:12:03,951 - INFO - manager.py:106 - wpyscripts.manager - host: 127.0.0.1 port: 53001

2018-03-09 18:12:04,091 - DEBUG - uiautomator_manager.py:34 - wetest - Start UIAutomator
2018-03-09 18:12:07,101 - DEBUG - uiautomator_manager.py:37 - wetest - Exit uiautomator
2018-03-09 18:12:08,490 - INFO - connectionpool.py:214 - libs.urllib3.connectionpool - Starting new HTTP connection (1):
 127.0.0.1
2018-03-09 18:12:09,510 - DEBUG - connectionpool.py:401 - libs.urllib3.connectionpool - "POST /jsonrpc/0 HTTP/1.1" 200 3
71
2018-03-09 18:12:09,512 - DEBUG - baisc_operater.py:390 - wetest - Find pakcage com.ejoy.a2.inhouse
Retry...10053

**Comment by lazydao** [comment]
def test():
    logger = manager.get_logger()
    device = manager.get_device()

    # version=engine.get_sdk_version()
    # logger.debug("Version Information : {0}".format(version))

    # 启动游戏
    device.launch_app(local_package)
    wait_for_package(local_package)
    time.sleep(10)
    subprocess.call("adb shell input tap 400 400")
    time.sleep(10)
    global engine
    engine = manager.get_engine()
    version = None
    for i in range(30):
        try:
            version = engine.get_sdk_version()
            if version:
                logger.debug(version)
                break
        except:
            time.sleep(2)
