### ISSUE TITLE
根据教程写的代码报错，求指导

### ISSUE THREAD

**Issue by youshiki123** [Tencent/GAutomator#23]
2017-05-16 10:21:58,053 - INFO - manager.py:104 - wpyscripts.manager - None
2017-05-16 10:21:58,053 - INFO - manager.py:106 - wpyscripts.manager - host: 127.0.0.1 port: 53001
Traceback (most recent call last):
  File "E:/svn/python/GAutomator/sample_test.py", line 6, in <module>
    from testcase.tools import *
  File "E:\svn\python\GAutomator\testcase\tools.py", line 12, in <module>
    from wpyscripts.tools.baisc_operater import *
  File "E:\svn\python\GAutomator\wpyscripts\tools\baisc_operater.py", line 22, in <module>
    engine = manager.get_engine()
  File "E:\svn\python\GAutomator\wpyscripts\manager.py", line 107, in get_engine
    get_engine.instance = GameEngine(hostip, local_port)
  File "E:\svn\python\GAutomator\wpyscripts\wetest\engine.py", line 108, in __init__
    self.socket = SocketClient(self.address, self.port)
  File "E:\svn\python\GAutomator\wpyscripts\common\socket_client.py", line 23, in __init__
    self.socket.connect((self.host, self.port))
  File "C:\Python27\lib\socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 10061]

**Comment by lilin22** [comment]
同问，可否解答

**Comment by wukenaihe** [comment]
一般情况检查adb是否设置在环境变量了，where adb可以查看。检查游戏是否已经拉起，并且在当前手机最前面的应用。检查游戏是否集成GAutomator SDK
