### ISSUE TITLE
demo无法运行，游戏已经拉起，但无法运行demo

### ISSUE THREAD

**Issue by NickyWu123** [Tencent/GAutomator#42]
wutianyang$ python sample.py 
2018-03-21 16:57:47,722 - INFO - manager.py:104 - wpyscripts.manager - None
2018-03-21 16:57:47,722 - INFO - manager.py:106 - wpyscripts.manager - host: 127.0.0.1 port: 53001

2018-03-21 16:57:47,756 - DEBUG - uiautomator_manager.py:35 - wetest - Start UIAutomator
2018-03-21 16:57:50,764 - DEBUG - uiautomator_manager.py:38 - wetest - Exit uiautomator
Traceback (most recent call last):
  File "sample.py", line 196, in <module>
    main()
  File "sample.py", line 190, in main
    test_interaction()
  File "sample.py", line 33, in wrapped
    enter = engine.find_element(button)
  File "/Users/wutianyang/Desktop/GAutomator-master/wpyscripts/wetest/engine.py", line 155, in find_element
    ret = self.socket.send_command(Commands.FIND_ELEMENTS, [name])
  File "/Users/wutianyang/Desktop/GAutomator-master/wpyscripts/common/socket_client.py", line 111, in send_command
    raise e
wpyscripts.common.wetest_exceptions.WeTestSDKError: recv length is None?

模拟器是genymotion，在模拟器打开了demo，然后运行sample.py 显示此异常

**Comment by wukenaihe** [comment]
@NickyWu123 确认下adb是否可以正常使用.where adb能够确认adb是否已成功设置成环境变量
