### ISSUE TITLE
调用组件上的方法参数错误（failed to convert parameters, parameterType: Single）

### ISSUE THREAD

**Issue by linjinglan** [Tencent/GAutomator#58]
组件上有一方法    FindPath(float x, float y, float z)，
然后在python测试案例中调用该方法，
main_player = engine.find_element("MainPlayer")
param = []
param.append(-20)
param.append(16)
param.append(-11)
engine.call_component_method(main_player, "NavigationAgent", "FindPath", param)
运行时报错，如下
Traceback (most recent call last):
  File "mytest.py", line 31, in <module>
    test()
  File "mytest.py", line 23, in test
    engine.call_component_method(main_player, "NavigationAgent", "GFindPath", params)
  File "E:\Downloads\wetest_sdk\GAutomator\wpyscripts\wetest\engine.py", line 828, in call_component_method
    "methodName": method, "parameters": params})
  File "E:\Downloads\wetest_sdk\GAutomator\wpyscripts\common\socket_client.py", line 111, in send_command
    raise e
wpyscripts.common.wetest_exceptions.WeTestSDKError: Error code: 7 msg: failed to convert parameters

看上去是说我的参数类型错误，然后用 engine.get_component_methods 获得这个方法的描述如下

{u'returnType': u'Void', u'parameterTypes': [u'Single', u'Single', u'Single'], u'methodName': u'FindPath'}

这个Single是啥类型 ？

**Comment by linjinglan** [comment]
我把游戏Component里的方法参数改成string，然后才能调用正常

**Comment by tianshanfz** [comment]
怀疑是C#端反射调用组件方法的时候 转single失败了， 试试改成浮点数传进去看。
