### ISSUE TITLE
GAutomatorView在update后没有获取到屏幕截图

### ISSUE THREAD

**Issue by sarazhao** [Tencent/GAutomator#63]
手机安装了domo并拉起，GAutomatorView2.2在update screen后没有获取到屏幕截图，请帮忙看看
![Screenshot_20190422-143630_Free Fire](https://user-images.githubusercontent.com/6415492/57677298-0e901000-7659-11e9-89de-386c710471ca.jpg)

**Comment by tianshanfz** [comment]
GAutomatorView是通过screencap截图的。
建议：
1.先手动执行adb shell screencap -p /sdcard/screen.png 看有没有报错。
2.在GAutomatorView的app\snapshot目录下的wetest.png是否正常。
以上两步有异常的话很可能是手机的问题
3..在GAutomatorView的app\logs目录下找update后有没有报错信息。

**Comment by sarazhao** [comment]
今天试下来有时候正常，有时候还是无法显示，显示异常的时候查看GAutomatorView的app\snapshot截图是没有全的，像下图一样
![图片](https://user-images.githubusercontent.com/6415492/60956423-5ec3df80-a335-11e9-84af-66e7937f10a0.png)

1、手动执行adb shell screencap -p /sdcard/screen.png ，可以正确截图

> 在GAutomatorView的app\snapshot目录下的wetest.png是否正常

 不正常，截图只显示了一半，但手机tmp下图片正确

`
2019-07-10 17:03:56  [ JavaFX Application Thread:824715 ] - [ ERROR ]  showGameData failed !
java.lang.NullPointerException
	at com.tencent.gautomatorview.view.MainPageController.showGameData(Unknown Source)
	at com.tencent.gautomatorview.MainApp.closeSyncPage(Unknown Source)
	at com.tencent.gautomatorview.view.SyncPageController$1$5.run(Unknown Source)
	at com.sun.javafx.application.PlatformImpl.lambda$null$172(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$173(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$147(WinApplication.java:177)
	at java.lang.Thread.run(Thread.java:748)
`
上面是update之后的errorlog，有时候是Image failed to load的错误：

`
2019-07-10 17:03:56  [ JavaFX Application Thread:824714 ] - [ ERROR ]  Image failed to load.
javax.imageio.IIOException: Error reading PNG image data
	at com.sun.imageio.plugins.png.PNGImageReader.readImage(PNGImageReader.java:1345)
	at com.sun.imageio.plugins.png.PNGImageReader.read(PNGImageReader.java:1614)
	at javax.imageio.ImageIO.read(ImageIO.java:1448)
	at javax.imageio.ImageIO.read(ImageIO.java:1308)
	at com.tencent.gautomatorview.view.MainPageController.showGameData(Unknown Source)
	at com.tencent.gautomatorview.MainApp.closeSyncPage(Unknown Source)
	at com.tencent.gautomatorview.view.SyncPageController$1$5.run(Unknown Source)
	at com.sun.javafx.application.PlatformImpl.lambda$null$172(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$173(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$147(WinApplication.java:177)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.EOFException: Unexpected end of ZLIB input stream
	at java.util.zip.InflaterInputStream.fill(InflaterInputStream.java:240)
	at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:158)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at com.sun.imageio.plugins.png.PNGImageReader.decodePass(PNGImageReader.java:1119)
	at com.sun.imageio.plugins.png.PNGImageReader.decodeImage(PNGImageReader.java:1223)
	at com.sun.imageio.plugins.png.PNGImageReader.readImage(PNGImageReader.java:1338)
	... 13 more
`

**Comment by sarazhao** [comment]
难不成是手机渣？又找了一台高端Android似乎正常了。
