### ISSUE TITLE
subprocess.Popen()的shell参数问题

### ISSUE THREAD

**Issue by dragonlzl** [Tencent/GAutomator#64]
运行demo时，报错了：
2019-06-24 11:20:37,165 - DEBUG - uiautomator_manager.py:108 - wetest - Start UIAutomator
Traceback (most recent call last):
  File "/Users/dragonlin/study/GAutomator-master/GAutomatorAndroid/testcase/sample.py", line 21, in <module>
    test()
  File "/Users/dragonlin/study/GAutomator-master/GAutomatorAndroid/testcase/sample.py", line 8, in test
    engine=manager.get_engine()
  File "/Users/dragonlin/study/GAutomator-master/GAutomatorAndroid/wpyscripts/manager.py", line 108, in get_engine
    ui_device = uiauto.get_uiautomator()
  File "/Users/dragonlin/study/GAutomator-master/GAutomatorAndroid/wpyscripts/uiautomator/uiautomator_manager.py", line 130, in get_uiautomator
    port=_init()
  File "/Users/dragonlin/study/GAutomator-master/GAutomatorAndroid/wpyscripts/uiautomator/uiautomator_manager.py", line 121, in _init
    init_uiautomator()
  File "/Users/dragonlin/study/GAutomator-master/GAutomatorAndroid/wpyscripts/uiautomator/uiautomator_manager.py", line 109, in init_uiautomator
    uiautomator_process=excute_adb_process_daemon("shell uiautomator runtest uiautomator-stub.jar -c com.github.uiautomatorstub.Stub")
  File "/Users/dragonlin/study/GAutomator-master/GAutomatorAndroid/wpyscripts/common/adb_process.py", line 49, in excute_adb_process_daemon
    p = subprocess.Popen(command, shell=shell, stderr=subprocess.STDOUT, stdout=subprocess.PIPE)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'adb shell uiautomator runtest uiautomator-stub.jar -c com.github.uiautomatorstub.Stub': 'adb shell uiautomator runtest uiautomator-stub.jar -c com.github.uiautomatorstub.Stub'

查了一下，是cmd为字符串的问题，把
 p = subprocess.Popen(command, shell=shell, stderr=subprocess.STDOUT, stdout=subprocess.PIPE)
的 shell=shell 改成True才行。

**Comment by tianshanfz** [comment]
确实 在Mac上应该会受影响, 谢谢 已修改
