### ISSUE TITLE
求助：报错NameError: global name 'urllib3' is not defined怎么办

### ISSUE THREAD

**Issue by sarazhao** [Tencent/GAutomator#65]
unity教程的5.1屏幕尺寸与转向，保存代码运行后报错：
`
2019-07-11 17:51:04,701 - WARNING - device.py:172 - wetest - Traceback (most recent call last):
  File "F:\GAutomator\wpyscripts\wetest\device.py", line 169, in get_top_package_activity
    return TopActivity("", self.ui_device.info["currentPackageName"])
  File "F:\GAutomator\libs\uiauto\uiautomator.py", line 693, in info
    return self.server.jsonrpc.deviceInfo()
  File "F:\GAutomator\libs\uiauto\uiautomator.py", line 469, in wrapper
    URLError = urllib3.exceptions.HTTPError if os.name == "nt" else urllib2.URLError
### NameError: global name 'urllib3' is not defined

`
尝试着import了wpyscripts下的uiautomator_manager、wetest下的device、libs下的uiautomator但是没有解决问题，请问：NameError: global name 'urllib3' is not defined
想要正确运行这段代码，需要import哪些文件，或者需要哪些操作？非常感谢

**Comment by sarazhao** [comment]
试了下直接运行sample/devices_tester.py，报错
![图片](https://user-images.githubusercontent.com/6415492/61101747-803fdb00-a49d-11e9-8cef-8ee904baf587.png)
百度了一下10061说是服务被拒绝，不知道要怎么修改，请大佬指点

**Comment by sarazhao** [comment]
同事帮忙看了一下，原来是device offline了。
